name = "Fabulously Optimized"
author = "robotkoer"
version = "14.0.0-alpha.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bfa5906e852e7f3891094a509e844393ed20d6c3e62ad509fe3eaddda293503d"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
